Run `rails app:update` and manually merge config changes
The default update process overwrote some of our configs, so I
manually reverted those changes. Most of the changes were to
comments, additional configs, and imports, which are intact here.
I've also run `rubocop -a` to fix up linting issues introduced by
the update.

This update should fix issues we're seeing with the Time module
in the Rails 6.1 upgrade:

```
NoMethodError: undefined method `hour' for 1:Integer
/var/lib/jenkins/workspace/dependabot_bundler_rails-6.1.3_2/config/environments/test.rb:19:in `block in <top (required)>'
/var/lib/jenkins/bundles/ruby/2.7.0/gems/railties-6.1.3/lib/rails/railtie.rb:234:in `instance_eval'
```

We did consider explicitly requiring "active_support/time" in
config/application.rb, but the `rails app:update` applies a more
granular fix to each of our config/environments/*.rb instead.