Remove unused classes
- attempting to fix Sass compilation warnings, discovered that classes do not appear to be in use, so removing
- e.g. `taxon-page__featured-image` contained a width calculation that was causing a Sass compilation error: `Using / for division outside of calc() is deprecated`