Replace Dalli store with MemCacheStore
Dalli store is not supported in Rails 6.1:
https://github.com/petergoldstein/dalli/issues/771

The fix is to swap out for MemCacheStore, as we've done here:
https://github.com/alphagov/local-links-manager/pull/751

Without this change, a write to the cache causes this exception:

```
NoMethodError
undefined method `dup_value!' for #<String:0x00007f9cf66fb130>
```

That said, we still need the dalli gem, otherwise we get this
error:

```
Could not find cache store adapter for mem_cache_store (cannot load such file -- dalli)
/app/config/environment.rb:5:in `<top (required)>'
```