Fix flaky person test
This test intermittently fails in CI with:

```
​1) Person page displays the person page
   ​Failure/Error: expect(page).to have_title("Rufus Scrimgeour - GOV.UK")

   ​NoMethodError:
     ​undefined method `match?' for nil:NilClass
```

I think this could be because we're trying to load a "Random" content
item before each test run. The hope is that memoizing the content item
will mean that that the `title` is already set before the page loads.