Only use `better_errors` in development environment
This application uses `better_errors` to produce pretty error messages
when an error occurs.

This is great for development in a browser, but as the error is returned
as a HTML response, we don't ever see the error when running feature
tests (as Capybara thinks the page loaded ok). All we see is that the
test expectation fails.

Example of a failing test after this change:
```
 1) Topical Event pages afghanistan response topical event includes travel advice for Afghanistan
    Failure/Error:
      @content_item.content_item_data.dig("links", "organisations").map do |organisation|
        {
          content_id: organisation["content_id"],
          base_path: organisation["base_path"],
          title: organisation["title"],
          crest: organisation.dig("details", "logo", "crest"),
          brand: organisation.dig("details", "brand"),
        }
      end

    ActionView::Template::Error:
      undefined method `map' for nil:NilClass
    # ./app/models/topical_event.rb:111:in `organisations'
    # ./app/views/topical_events/show.html.erb:26:in `_app_views_topical_events_show_html_erb___4491315266640037643_67180'
    # ./spec/features/topical_event_spec.rb:71:in `block (3 levels) in <top (required)>'
    # ------------------
    # --- Caused by: ---
    # NoMethodError:
    #   undefined method `map' for nil:NilClass
    #   ./app/models/topical_event.rb:111:in `organisations'
```

However, the actual error was suppressed before this, making debugging
very difficult:
```
1) Topical Event pages afghanistan response topical event includes travel advice for Afghanistan
   Failure/Error: expect(page).to have_link(titleize_base_path(afghanistan_travel_advice_base_path), href: afghanistan_travel_advice_base_path)
     expected to find link "Foreign travel advice afghanistan" with href "/foreign-travel-advice/afghanistan" but there were no matches
   # ./spec/features/topical_event_spec.rb:72:in `block (3 levels) in <top (required)>'
```

By moving `better_errors` to only be included in the development
environment, we will see actual errors when running tests locally.