Patch the minitest assertions Cucumber is used for feature tests in this repo. The step definitions of these tests are written using minitest syntax. Somehow RSpec is poluting the assertions variable used by methods like assert, so we see "undefined method `+' for nil:NilClass (NoMethodError)" each time assert is called. This patch fixes this problem for the time being. Once the step definitions are rewritten in RSpec, this file can be removed.