Fix ministers preview when departments missing ordered_ministers
A number of preview issues were fixed in #3673 but it looks like
this was missed:

```
NoMethodError
undefined method `map' for nil:NilClass (NoMethodError)

        ministers: department_data.dig("links", "ordered_ministers").map do |minister_data|
                                                                    ^^^^
```

Sentry error: https://govuk.sentry.io/issues/5562581438/?project=202213&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=1h&stream_index=0